# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 01:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2016, 4, 15, 1, 40, 49, 667057, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
