# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceReviewItem',
            fields=[
                ('rClass', models.CharField(default='ecommreview', max_length=30)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='ok', max_length=10)),
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('writerId', models.CharField(blank=True, max_length=30, null=True)),
                ('writerName', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('crawlTime', models.DateTimeField(default=datetime.datetime.today)),
                ('createTime', models.DateTimeField(default=datetime.datetime.today)),
                ('commentCount', models.PositiveIntegerField(blank=True, null=True)),
                ('refCount', models.PositiveIntegerField(blank=True, null=True)),
                ('totalCount', models.PositiveIntegerField(blank=True, null=True)),
                ('agreeCount', models.PositiveIntegerField(blank=True, null=True)),
                ('refuseCount', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ecommercelistitem',
            name='rClass',
            field=models.CharField(default='ecommlist', max_length=30),
        ),
        migrations.AddField(
            model_name='ecommercereviewitem',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.EcommerceListItem'),
        ),
    ]
