# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20160421_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercereviewitem',
            name='reviewId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecommercereviewitem',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.EcommerceListItem'),
        ),
    ]
